apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: project-pod
        image: myproject:1.0
        ports:
        - containerPort: 8080
